## **DAY 4: Data Cleaning & Preprocessing**

<br>
<br>

### **PART 1 — What is Data Cleaning?**

Data cleaning is the process of fixing or removing incorrect, corrupted, incorrectly formatted, duplicate, or incomplete data within a dataset. When combining multiple data sources, there are many opportunities for data to be duplicated or mislabeled. If data is incorrect, outcomes and algorithms are unreliable, even though they may look correct.

### **Common Data Problems**

| Problem | Example |
| :--- | :--- |
| **Missing values** | `NaN` or `None` |
| **Duplicates** | Same row repeated |
| **Wrong datatype** | Date stored as text |
| **Outliers** | Salary = 9999999 |
| **Inconsistent text** | "Hyderabad" vs "hyd" |
| **Extra spaces** | " Phone " |

<br>
<br>

### **PART 2 — Missing Values**

Missing values occur when no data value is stored for the variable in an observation. This can happen due to human error, equipment failure, or data simply not being available.

#### **1. Detect and Count Missing Values**

We use `.isnull()` to create a boolean mask and `.sum()` to count the total missing values per column.

In [3]:
import pandas as pd
import numpy as np

# Creating a sample dataframe with various missing value types
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Age': [25, np.nan, 30, 22, 28, np.nan],
    'Salary': [50000, 54000, np.nan, 52000, 58000, 150000], # Frank is an outlier
    'City': ['New York', 'Los Angeles', None, 'Chicago', 'Miami', 'Miami']
}
df = pd.DataFrame(data)

print("Original DataFrame with Missing Values:")
display(df)

# 1. Detect and Count Missing Values
print("\nMissing values per column:")
print(df.isnull().sum())

Original DataFrame with Missing Values:

      Name   Age    Salary         City
0    Alice  25.0   50000.0     New York
1      Bob   NaN   54000.0  Los Angeles
2  Charlie  30.0       NaN         None
3    David  22.0   52000.0      Chicago
4      Eve  28.0   58000.0        Miami
5    Frank   NaN  150000.0        Miami

Missing values per column:
Name      0
Age       2
Salary    1
City      1
dtype: int64

#### **2. Handling Missing Values**

- **Remove Rows:** Use `df.dropna()` to remove rows with any missing values.
- **Fill with Mean:** Good for numerical data with no extreme outliers.
- **Fill with Median:** Better for numerical data when outliers are present.
- **Fill with Mode:** Used for categorical columns.

In [4]:
# 2. Handling Missing Values

# Fill 'Age' with Mean (No extreme outliers)
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Fill 'Salary' with Median (Better because of the outlier Frank)
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

# Fill 'City' with Mode (Most frequent value)
df['City'] = df['City'].fillna(df['City'].mode()[0])

print("DataFrame after filling missing values:")
display(df)

DataFrame after filling missing values:

      Name    Age    Salary         City
0    Alice  25.00   50000.0     New York
1      Bob  26.25   54000.0  Los Angeles
2  Charlie  30.00   54000.0        Miami
3    David  22.00   52000.0      Chicago
4      Eve  28.00   58000.0        Miami
5    Frank  26.25  150000.0        Miami

### **PART 3 — Handling Duplicates**

Duplicate data occurs when the same observation is recorded multiple times. This can skew statistical results and lead to overfitting in machine learning models.

#### **1. Detect Duplicates**
Use `df.duplicated()` to identify duplicate rows.

In [19]:
# Create data with duplicates
data_dupes = {
    'ID': [101, 102, 102, 103, 104, 101],
    'Name': ['Alice', 'Bob', 'Bob', 'Charlie', 'David', 'Alice']
}
df_dupe = pd.DataFrame(data_dupes)

print("Data with Duplicates:")
display(df_dupe)

# Count duplicates
print(f"\nNumber of duplicate rows: {df_dupe.duplicated().sum()}")

df_dupe = df_dupe.drop_duplicates()

print("\nData after removing duplicates:")
display(df_dupe)

Data with Duplicates:

    ID     Name
0  101    Alice
1  102      Bob
2  102      Bob
3  103  Charlie
4  104    David
5  101    Alice

Number of duplicate rows: 2

Data after removing duplicates:

    ID     Name
0  101    Alice
1  102      Bob
3  103  Charlie
4  104    David

#### **2. Remove Duplicates**
Use `df.drop_duplicates()` to keep only unique entries.

In [6]:
# Remove duplicates and keep the first occurrence
df_unique = df_dupe.drop_duplicates(keep='first')

print("Cleaned Data (Unique rows only):")
display(df_unique)

Cleaned Data (Unique rows only):

    ID     Name
0  101    Alice
1  102      Bob
3  103  Charlie
4  104    David

<br>
<br>

### **PART 4 — Incorrect Datatypes**

Sometimes data is loaded with the wrong type (e.g., a date or a number stored as a string). Ensuring correct datatypes is essential for mathematical operations and model performance.

#### **1. Check Datatypes**
Use `df.dtypes` to see the current format of each column.

In [7]:
# Example: Check datatypes
print("Current datatypes:")
print(df.dtypes)

Current datatypes:
Name       object
Age       float64
Salary    float64
City       object
dtype: object

#### **2. Convert Datatypes**
We can use `pd.to_datetime()` for dates and `.astype()` for numerical conversions.

In [8]:
# Sample data with mixed types
data_types = {
    'Date': ['2023-01-01', '2023-01-02'],
    'Price': ['100', '200']
}
df_types = pd.DataFrame(data_types)

# Convert String to Datetime
df_types['Date'] = pd.to_datetime(df_types['Date'])

# Convert String to Integer
df_types['Price'] = df_types['Price'].astype(int)

print("Converted datatypes:")
print(df_types.dtypes)
display(df_types)

Converted datatypes:
Date     datetime64[ns]
Price             int64
dtype: object

        Date  Price
0 2023-01-01    100
1 2023-01-02    200

**Why is this important?**
- ML models require numerical consistency.
- Correct datatypes enable time-series analysis and arithmetic operations.

### **PART 5 — String Cleaning**

Text data often comes with inconsistencies such as mixed casing, leading/trailing spaces, or variations in naming (e.g., 'hyd' vs 'hyderabad'). Standardizing these strings is essential for accurate grouping and analysis.

In [9]:
# Sample data with messy strings
data_strings = {
    'City': [' HYDERABAD ', 'hyd', 'Chicago', 'chicago '],
    'Product': [' Laptop', 'Mouse ', ' Tablet ', 'Phone']
}
df_str = pd.DataFrame(data_strings)

print("Original Messy Strings:")
display(df_str)

# 1. Lowercase
df_str['City'] = df_str['City'].str.lower()

# 2. Remove Spaces (Strip)
df_str['City'] = df_str['City'].str.strip()
df_str['Product'] = df_str['Product'].str.strip()

# 3. Replace Values
df_str['City'] = df_str['City'].replace('hyd', 'hyderabad')

print("\nCleaned Strings:")
display(df_str)

Original Messy Strings:

          City   Product
0   HYDERABAD     Laptop
1          hyd    Mouse
2      Chicago   Tablet
3     chicago      Phone

Cleaned Strings:

        City Product
0  hyderabad  Laptop
1  hyderabad   Mouse
2    chicago  Tablet
3    chicago   Phone

<br>
<br>

### **PART 6 — Outlier Handling**

Outliers are data points that differ significantly from other observations. They can be caused by measurement errors or simply represent rare but valid occurrences. However, they can negatively impact the performance of many machine learning models.

Example:
`[10, 12, 13, 15, 1000]` -> `1000` is a clear outlier.

#### **1. Detect Outliers Using IQR (Interquartile Range)**

The IQR is the range between the first quartile (25th percentile) and the third quartile (75th percentile). Any data point outside $1.5 \times IQR$ below Q1 or above Q3 is typically considered an outlier.

**Formula:**
$IQR = Q3 - Q1$

**Bounds:**
- Lower Limit = $Q1 - 1.5 \times IQR$
- Upper Limit = $Q3 + 1.5 \times IQR$

In [10]:
# Calculate Q1 (25th percentile) and Q3 (75th percentile)
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)
IQR = Q3 - Q1

# Define bounds
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print(f"Salary IQR: {IQR}")
print(f"Lower Limit: {lower_limit}")
print(f"Upper Limit: {upper_limit}")

# Identify outliers
outliers = df[(df['Salary'] < lower_limit) | (df['Salary'] > upper_limit)]
print("\nOutliers detected:")
display(outliers)

Salary IQR: 4500.0
Lower Limit: 45750.0
Upper Limit: 63750.0

Outliers detected:

    Name    Age    Salary   City
5  Frank  26.25  150000.0  Miami

#### **2. Remove Outliers**
We filter the DataFrame to keep only the rows where the value falls within the calculated limits.

In [11]:
# Remove outliers
df_cleaned = df[(df['Salary'] >= lower_limit) & (df['Salary'] <= upper_limit)]

print("DataFrame after removing outliers (Frank should be gone):")
display(df_cleaned)

DataFrame after removing outliers (Frank should be gone):

      Name    Age   Salary         City
0    Alice  25.00  50000.0     New York
1      Bob  26.25  54000.0  Los Angeles
2  Charlie  30.00  54000.0        Miami
3    David  22.00  52000.0      Chicago
4      Eve  28.00  58000.0        Miami

<br>
<br>

### **PART 7 — Feature Scaling**

Feature scaling is a technique used to standardize the range of independent variables or features of data. In data processing, it is also known as data normalization and is generally performed during the data preprocessing step.

**Why Scaling?**
Features often have different ranges. For example, 'Salary' might be in the thousands, while 'Age' is under 100. If we don't scale, the machine learning model might assume the larger values (Salary) are more important than the smaller ones (Age).

#### **1. Standardization (Z-score Normalization)**
Standardization transforms data so that it has a **mean of 0** and a **standard deviation of 1**.

**Formula:**
$$z = \frac{x - \mu}{\sigma}$$
Where $\mu$ is the mean and $\sigma$ is the standard deviation.

In [12]:
from sklearn.preprocessing import StandardScaler

scaler_std = StandardScaler()

# We use the original df (with Frank) to see the effect of scaling on outliers
df['Scaled_Salary'] = scaler_std.fit_transform(df[['Salary']])

print("Data after Standardization (Mean ≈ 0, Std ≈ 1):")
display(df[['Name', 'Salary', 'Scaled_Salary']])

Data after Standardization (Mean ≈ 0, Std ≈ 1):

      Name    Salary  Scaled_Salary
0    Alice   50000.0      -0.546179
1      Bob   54000.0      -0.435092
2  Charlie   54000.0      -0.435092
3    David   52000.0      -0.490636
4      Eve   58000.0      -0.324005
5    Frank  150000.0       2.231003

#### **2. Normalization (Min-Max Scaling)**
Normalization scales the data into a fixed range, typically **0 to 1**.

**Formula:**
$$x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

In [13]:
from sklearn.preprocessing import MinMaxScaler

scaler_minmax = MinMaxScaler()

df['Normalized_Salary'] = scaler_minmax.fit_transform(df[['Salary']])

print("Data after Min-Max Normalization (Range: 0 to 1):")
display(df[['Name', 'Salary', 'Normalized_Salary']])

Data after Min-Max Normalization (Range: 0 to 1):

      Name    Salary  Normalized_Salary
0    Alice   50000.0               0.00
1      Bob   54000.0               0.04
2  Charlie   54000.0               0.04
3    David   52000.0               0.02
4      Eve   58000.0               0.08
5    Frank  150000.0               1.00

<br>
<br>

### **PART 8 — Encoding Categorical Data**

Most Machine Learning algorithms cannot handle text labels directly. They require numerical input. Therefore, we must convert categorical text data into a numerical format.

Two common techniques are:
1. **Label Encoding**: Assigns a unique integer to each category.
2. **One-Hot Encoding**: Creates new binary columns for each category (0 or 1).

#### **1. Label Encoding**
Label Encoding is useful when there is an inherent order in the categories (ordinal data), though it is often used for binary targets as well.

In [14]:
from sklearn.preprocessing import LabelEncoder

#IT BASCICALLY LABELS THE CITY EX :- (MIAMI: 2, NEWYORK: 3)

le = LabelEncoder()

# Creating a copy to keep the original clean
df_encoded = df.copy()

df_encoded['City_Encoded'] = le.fit_transform(df_encoded['City'])

print("Data after Label Encoding (City column):")
display(df_encoded[['Name', 'City', 'City_Encoded']])

Data after Label Encoding (City column):

      Name         City  City_Encoded
0    Alice     New York             3
1      Bob  Los Angeles             1
2  Charlie        Miami             2
3    David      Chicago             0
4      Eve        Miami             2
5    Frank        Miami             2

#### **2. One-Hot Encoding**
One-Hot Encoding is preferred when there is no natural order between categories (nominal data). It prevents the model from assuming that 'City 2' is 'greater' than 'City 1'.

In [15]:
# Using pandas get_dummies for One-Hot Encoding
df_final = pd.get_dummies(df_cleaned, columns=['City'])

print("Data after One-Hot Encoding (using the cleaned DataFrame):")
display(df_final)

Data after One-Hot Encoding (using the cleaned DataFrame):

,Name,Age,Salary,City_Chicago,City_Los Angeles,City_Miami,City_New York
0,Alice,25.00,50000.0,False,False,False,True
1,Bob,26.25,54000.0,False,True,False,False
2,Charlie,30.00,54000.0,False,False,True,False
3,David,22.00,52000.0,True,False,False,False
4,Eve,28.00,58000.0,False,False,True,False

<br>
<br>

### **PART 9 — Train Test Split**

Separating your data into a training set and a testing set is a fundamental step in machine learning.

**Why is this important?**
We train the model on one portion of the data (Training Set) and then evaluate its performance on a completely different portion (Testing Set). This tells us how well the model will perform on new, unseen data, preventing **overfitting**.

In [16]:
from sklearn.model_selection import train_test_split

# For demonstration, let's assume 'Salary' is our target variable (y)
# and the rest are features (X)
# We'll use our final one-hot encoded dataframe

X = df_final.drop('Salary', axis=1)
y = df_final['Salary']

# Split the data (80% Training, 20% Testing)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(f"Total samples: {len(X)}")
print(f"Training samples: {len(X_train)}")
print(f"Testing samples: {len(X_test)}")

print("\nFirst few rows of X_train:")
display(X_train.head())

Total samples: 5
Training samples: 4
Testing samples: 1

First few rows of X_train:

      Name   Age  City_Chicago  City_Los Angeles  City_Miami  City_New York
4      Eve  28.0         False             False        True          False
2  Charlie  30.0         False             False        True          False
0    Alice  25.0         False             False       False           True
3    David  22.0          True             False       False          False

<br>
<br>

### **PART 10 — Pipelines**

Pipelines are a way to automate the machine learning workflow. They allow you to bundle multiple steps (like scaling, encoding, and modeling) into a single object.

**Why use Pipelines?**
Instead of manually applying cleaning, scaling, and encoding to your training and testing sets separately, a Pipeline handles everything automatically. This prevents **data leakage** and makes your code much more efficient.

In [17]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

# Defining a simple pipeline
# 1. Scaling the data
# 2. Applying Linear Regression
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LinearRegression())
])

print("Pipeline created successfully!")
print(pipeline)

Pipeline created successfully!
Pipeline(steps=[('scaler', StandardScaler()), ('model', LinearRegression())])

<br>
<br>

## **PART 11 — FULL PRACTICE EXAMPLE**

In [35]:
import pandas as pd
import numpy as np

data = {
    "Name": ["A", "B", "B", "C"],
    "Age": [21, np.nan, np.nan, 25],
    "Salary": [30000, 40000, 40000, 999999],
    "City": ["Hyd ", "hyd", "Mumbai", None]
}

# Adding .copy() here ensures we have a fresh dataframe to work with
df = pd.DataFrame(data).copy()

In [46]:
import pandas as pd
import numpy as np

# Re-initialize to ensure we have all data points
data = {
    "Name": ["A", "B", "B", "C"],
    "Age": [21, np.nan, np.nan, 25],
    "Salary": [30000, 40000, 40000, 999999],
    "City": ["Hyd ", "hyd", "Mumbai", None]
}
df = pd.DataFrame(data)

# 1. FILL MISSING VALUES
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['City'] = df['City'].fillna(df['City'].mode()[0])

# 2. CLEAN STRINGS
df['City'] = df['City'].str.strip().str.lower()
df['City'] = df['City'].replace('hyd', 'hyderabad')

# 3. HANDLE OUTLIERS
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)
IQR = Q3 - Q1

if IQR == 0:
    # Fallback for very small datasets where IQR fails
    upper_bound = df['Salary'].median() * 5
    lower_bound = 0
else:
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

print(f"Lower Bound: {lower_bound}, Upper Bound: {upper_bound}")

# Filter keeping valid data (A, B) and removing the 999k (C)
df = df[(df['Salary'] >= lower_bound) & (df['Salary'] <= upper_bound)].copy()

# 4. REMOVE DUPLICATES
df = df.drop_duplicates().copy()

print("\nFinal Cleaned Data (Row A now correctly preserved!):")
display(df)

Lower Bound: -326249.625, Upper Bound: 643749.375

Final Cleaned Data (Row A now correctly preserved!):

  Name   Age  Salary       City
0    A  21.0   30000  hyderabad
1    B  23.0   40000  hyderabad
2    B  23.0   40000     mumbai